---
title: "Case_Study"
output: github_document
---

```{r setup,include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =0.6,
  out.width = "90%"
) 

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


## Load a dataset
```{r}
library(p8105.datasets)
data(nyc_airbnb)
```

* Look at price and room type..

```{r}
nyc_airbnb = nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(borough = neighbourhood_group)

  
```

let count things --janitor::tabyl
```{r}
nyc_airbnb %>% 
  janitor::tabyl(borough,room_type)
```
it is the same thing as janitor ::tabyl
```{r}
nyc_airbnb %>% 
  count(borough,room_type) %>% 
  pivot_wider(names_from = room_type,
              values_from = n)
```



```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) + geom_point() + facet_grid(.~room_type)
  
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price = mean(price,na.r = TRUE)) %>% 
  arrange(mean_price)

```

coord_flip --- x axis and y axis exchange the places 
reorder - take the median of second variable, usually the second one is numeric value
```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan", price <= 1000) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood,price)) %>% 
  ggplot(aes(x=neighbourhood, y= price)) + 
  geom_boxplot() +
  coord_flip() +
  facet_grid(.~room_type)

```
Price vs location
```{r}
nyc_airbnb %>% 
  filter(price<500) %>% 
  sample_n(5000) %>% 
  ggplot(aes(x=lat, y= long, color = price))+
  geom_point(alpha =0.5)
  
```


## retry leaflet
```{r,eval=FALSE}
library(leaflet)
nyc_airbnb %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers( ~lat, ~ long)
```

